# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  inventorymanager:
    image: inventorymanager
    build:
      context: .
      dockerfile: HomeInventoryManager.InventoryManager/Dockerfile
    ports:
      - 5115:5115
      - 8085:8085
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5115;http://+:8085
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HIM_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${HIM_CERT_PATH}
      - CUSTOMCONNSTR_DefaultConnection=${CUSTOMCONNSTR_DefaultConnection}
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    depends_on:
      - inventorydatabase
    links:
      - inventorydatabase

  inventorydatabase:
    image: inventorydb
    build: 
      context: Database/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_APPUSERNAME=${DB_APPUSERNAME}
      - DB_APPUSERPASSWORD=${DB_APPUSERPASSWORD}
    ports:
      - 5432:5432

  inventoryclient:
    image: inventoryclient
    build:
      context: .
      dockerfile: home-inventory-client/Dockerfile
    ports:
      - 8000:3000
    depends_on:
      - inventorymanager
    links:
      - inventorymanager
