# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  homeinventorymanagerinventorymanager:
    image: homeinventorymanagerinventorymanager
    build:
      context: .
      dockerfile: HomeInventoryManager.InventoryManager/Dockerfile
    ports:
      - 5115:5115
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
