version: '3.3'
services:
  postgres-postgresql:
    image: postgres:15.1
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_APPUSERNAME=${DB_APPUSERNAME}
      - DB_APPUSERPASSWORD=${DB_APPUSERPASSWORD}
    ports:
      - 5432:5432
